# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- pipeline

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    
  displayName: 'npm install'

-
- script: |
    docker pull hungphaminfo/react-shopping-cart
    docker run -it -p 3000:3000 hungphaminfo/react-shopping-cart
    displayName: 'Pull and Deploy Docker Image'
    
  displayName: 'npm install'
- script: |
    npm run test
  displayName: 'UI Automation Test'